name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics: 
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: trungpq163
          template: classic
          base: ""
          config_timezone: Asia/Saigon
          #plugin_calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          #plugin_topics
          #plugin_topics_sort: stars    # Sort by most starred topics
          #plugin_topics_mode: mastered # Display icons instead of labels
          #plugin_topics_limit: 0       # Disable limitations
          #plugin_people
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_types: followers, following
          #
          plugin_languages: yes
          plugin_languages_ignored: html, css                          # List of languages to ignore
          plugin_languages_skipped: MikuMikuDanceE_v932x64                       # List of repositories to skip
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..." # Make most used languages orange and JavaScript red
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                               # Hides all languages less than 2%
